# SPDX-License-Identifier: MIT
---
# manage_packages/tasks/apt.yml

- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ manage_packages_resolved_apt_install }}"
    state: present
    update_cache: true
  when: manage_packages_resolved_apt_install | length > 0
  become: true
  become_method: ansible.builtin.sudo

- name: Remove apt packages
  ansible.builtin.apt:
    name: "{{ manage_packages_resolved_apt_remove }}"
    state: absent
    purge: "{{ manage_packages_apt_remove_purge }}"
    autoremove: "{{ manage_packages_apt_remove_purge }}"
  when: manage_packages_resolved_apt_remove | length > 0
  become: true
  become_method: ansible.builtin.sudo
