# SPDX-License-Identifier: MIT
---
# tasks file for manage_packages: resolve-lists

# This step enumerates each preset name (e.g. ubuntu_desktop_base) to
# preapre to iterate over the install / remove lists it contains.
- name: Consume the package data for each active preset
  ansible.builtin.set_fact:
    manage_packages_active_preset_dicts: >-
      {{ manage_packages_active_presets | map('extract', manage_packages_presets) | list }}

# Iterate over the install / remove lists of each active preset.
- name: Flatten all packages from each active preset into install and remove lists
  ansible.builtin.set_fact:
    manage_packages_resolved_apt_install: >-
      {{ (manage_packages_apt_install + (manage_packages_active_preset_dicts | map(attribute='apt_install', default=[]) | list | flatten)) | unique }}
    manage_packages_resolved_apt_remove: >-
      {{ (manage_packages_apt_remove + (manage_packages_active_preset_dicts | map(attribute='apt_remove', default=[]) | list | flatten)) | unique }}
    manage_packages_resolved_dnf_install: >-
      {{ (manage_packages_dnf_install + (manage_packages_active_preset_dicts | map(attribute='dnf_install', default=[]) | list | flatten)) | unique }}
    manage_packages_resolved_dnf_remove: >-
      {{ (manage_packages_dnf_remove + (manage_packages_active_preset_dicts | map(attribute='dnf_remove', default=[]) | list | flatten)) | unique }}
    manage_packages_resolved_snap_install: >-
      {{ (manage_packages_snap_install + (manage_packages_active_preset_dicts | map(attribute='snap_install', default=[]) | list | flatten)) | unique }}
    manage_packages_resolved_snap_remove: >-
      {{ (manage_packages_snap_remove + (manage_packages_active_preset_dicts | map(attribute='snap_remove', default=[]) | list | flatten)) | unique }}
    manage_packages_resolved_flatpak_install: >-
      {{ (manage_packages_flatpak_install + (manage_packages_active_preset_dicts | map(attribute='flatpak_install', default=[]) | list | flatten)) | unique }}
    manage_packages_resolved_flatpak_remove: >-
      {{ (manage_packages_flatpak_remove + (manage_packages_active_preset_dicts | map(attribute='flatpak_remove', default=[]) | list | flatten)) | unique }}
    # TODO: Add winget here.
